# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VIRAUI(object):
    def setupUi(self, VIRAUI):
        VIRAUI.setObjectName("VIRAUI")
        VIRAUI.resize(1225, 861)
        self.centralwidget = QtWidgets.QWidget(VIRAUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1241, 831))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 871, 671))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("LCPT.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 750, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("background-color: rgb(8, 90, 141);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1110, 750, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background-color: rgb(8, 90, 141);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -60, 471, 221))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("llll.gif"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, -30, 391, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("llll.gif"))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(460, 10, 321, 87))
        self.textEdit.setStyleSheet("background:transparent;")
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 440, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-90, 350, 401, 161))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Cad.gif"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(930, 350, 331, 181))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Cad.gif"))
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.textEdit.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        VIRAUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VIRAUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 26))
        self.menubar.setObjectName("menubar")
        VIRAUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VIRAUI)
        self.statusbar.setObjectName("statusbar")
        VIRAUI.setStatusBar(self.statusbar)

        self.retranslateUi(VIRAUI)
        QtCore.QMetaObject.connectSlotsByName(VIRAUI)

    def retranslateUi(self, VIRAUI):
        _translate = QtCore.QCoreApplication.translate
        VIRAUI.setWindowTitle(_translate("VIRAUI", "viravira"))
        self.pushButton.setText(_translate("VIRAUI", "RUN"))
        self.pushButton_2.setText(_translate("VIRAUI", "EXIT"))
        self.textEdit.setHtml(_translate("VIRAUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">VIRA</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:48pt; font-weight:600; color:#ffffff;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("VIRAUI", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VIRAUI = QtWidgets.QMainWindow()
    ui = Ui_VIRAUI()
    ui.setupUi(VIRAUI)
    VIRAUI.show()
    sys.exit(app.exec_())
